# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93a6e6d9239041335626409a3a04a26fc68e58be1cde4a8b6230846b40fe497fb948b30f28ad16b30a3d492e08b2e19964a1fa03e9e9e9f5fdbd4fb4d186e12e

test:
  secret_key_base: e854305e6662a830d76095446ca593535cbd3e85868236271ae5a2eb0a33188d62f3c8ab621d829c9086c4c35f75a90b90b83a653fc3d718e9df5603ba16a33c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
